### ISSUE TITLE
有点问题。

### ISSUE THREAD

**Issue by ylmyg** [coderpage/Mine#12]
1 更新的网址已经访问不到了
2 在图标分析 日消费折线图  点击月消费折线图 再点击日消费折线图会退出
12-03 15:58:33.834 745-745/com.coderpage.mine E/MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
        at java.util.ArrayList.get(ArrayList.java:310)
at com.coderpage.mine.app.tally.chart.ChartActivity.lambda$setupMonthlyLineChart$1(ChartActivity.java:247)
        at com.coderpage.mine.app.tally.chart.ChartActivity$$Lambda$3.getFormattedValue(Unknown Source)
        at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
        at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
        at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:331)
        at com.github.mikephil.charting.charts.Chart.setData(Chart.java:304)
        at com.coderpage.mine.app.tally.chart.ChartActivity.showDailyExpenseLineChart(ChartActivity.java:339)
        at com.coderpage.mine.app.tally.chart.ChartActivity.displayUserActionResult(ChartActivity.java:474)
        at com.coderpage.mine.app.tally.chart.ChartActivity.displayUserActionResult(ChartActivity.java:65)
        at com.coderpage.framework.PresenterImpl$2.onModelUpdated(PresenterImpl.java:122)
        at com.coderpage.mine.app.tally.chart.ChartModel.deliverUserAction(ChartModel.java:198)
        at com.coderpage.mine.app.tally.chart.ChartModel.deliverUserAction(ChartModel.java:40)
        at com.coderpage.framework.PresenterImpl.onUserAction(PresenterImpl.java:113)
        at com.coderpage.mine.app.tally.chart.ChartActivity.lambda$showChartModeSwitchPopup$3(ChartActivity.java:577)
        at com.coderpage.mine.app.tally.chart.ChartActivity$$Lambda$4.onItemClick(Unknown Source)
        at android.widget.AdapterView.performItemClick(AdapterView.java:314)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1162)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3102)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:3979)
        at android.widget.HwAbsListView.onTouchUp(HwAbsListView.java:465)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3731)
        at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:124)
        at android.view.View.dispatchTouchEvent(View.java:9399)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2045)
        at android.view.View.dispatchPointerEvent(View.java:9619)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4471)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4337)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3869)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3922)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3888)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4014)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3896)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4071)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3869)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3922)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3888)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3896)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3869)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6170)
    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRo

**Comment by ylmyg** [comment]
逻辑有点绕脑，MVP模式有点复杂，有些确实看不懂为什么这样写。

**Comment by liuchao0206** [comment]
新版本应该没有这个问题了。用 MVVM 重写了
